spring:
  application:
    name: eureka
eureka:
  client:
    service-url:
      defaultZone : http://eureka2:8762/eureka
    fetch-registry: false
  instance:
    prefer-ip-address: true

server:
  port: 8761
