GET  http://localhost:8080/product/list

###

## 第一个product是应用的名字
GET http://localhost:9000/product/product/list

###

GET http://localhost:9000/config-server/order-dev.yml


###

GET http://116.196.118.178:8082/order-dev.yml

###

GET http://localhost:9000/myProduct/product/list

###

## 测试几个Post请求
POST http://localhost:8080/product/listForProductId
Content-Type: application/json

["157875196366160022","157875227953464068"]

###

POST http://localhost:9000/product/product/listForProductId
Content-Type: application/json


["157875196366160022","157875227953464068"]

###

## 来一个带cookie访问的：

GET http://localhost:9000/myProduct1/product/list
Cookie: name=123

###

## 必须带token来访问：

GET http://localhost:9000/myProduct1/product/list?token=111111


###

## 买家登陆：

GET http://localhost:9000/user/user/login/buyerLogin?openId=abc

###

## 卖家登陆：
GET http://localhost:9000/user/user/login/sellerLogin?openId=xyz

###

# 订单创建

POST http://localhost:9000/order/order/create
Content-Type: application/json
Cookie: openid=abc

{
  "name": "杨鑫",
  "phone": "18580090476",
  "openid": "abc",
  "address": "重庆市",
  "items": [
    {
      "productId": "157875196366160022",
      "productQuantity": 1
    }
  ]
}

###

# 订单完结

POST http://localhost:9000/order/order/finish?orderId=O9126925371319787520
Content-Type: application/json
Cookie: token=256fbfbe-d937-408f-a90b-d36204107ca0

###
